In [2]:
import pandas as pd

In [3]:
marketing_customer_analysis_cleaned_lab6 = pd.read_csv('marketing_customer_analysis_cleaned_lab6.csv')

In [4]:
marketing_customer_analysis_cleaned_lab6 = marketing_customer_analysis_cleaned_lab6.drop('Unnamed: 0', axis=1) 

In [5]:
marketing_customer_analysis_cleaned_lab6 = marketing_customer_analysis_cleaned_lab6.drop('Effective To Date', axis=1) 

In [46]:
marketing_customer_analysis_cleaned_lab6.head()

Customer       State  Customer Lifetime Value  Coverage Education  \
0  DK49336     Arizona              4809.216960     Basic   College   
1  KX64629  California              2228.525238     Basic   College   
2  LZ68649  Washington             14947.917300     Basic  Bachelor   
3  XL78013      Oregon             22332.439460  Extended   College   
4  QA50777      Oregon              9025.067525   Premium  Bachelor   

  EmploymentStatus Gender  Income Location Code Marital Status  ...  \
0         Employed      M   48029      Suburban        Married  ...   
1       Unemployed      F       0      Suburban         Single  ...   
2         Employed      M   22139      Suburban         Single  ...   
3         Employed      M   49078      Suburban         Single  ...   
4    Medical Leave      F   23675      Suburban        Married  ...   

   Number of Open Complaints  Number of Policies     Policy Type  \
0                   0.000000                   9  Corporate Auto   
1                   0.000000                   1   Personal Auto   
2                   0.000000                   2   Personal Auto   
3                   0.000000                   2  Corporate Auto   
4                   0.384256                   7   Personal Auto   

         Policy  Renew Offer Type Sales Channel Total Claim Amount  \
0  Corporate L3            Offer3         Agent         292.800000   
1   Personal L3            Offer4   Call Center         744.924331   
2   Personal L3            Offer3   Call Center         480.000000   
3  Corporate L3            Offer2        Branch         484.013411   
4   Personal L2            Offer1        Branch         707.925645   

   Vehicle Class Vehicle Size  response Rate  
0  Four-Door Car      Medsize              0  
1  Four-Door Car      Medsize              0  
2            SUV      Medsize              0  
3  Four-Door Car      Medsize              1  
4  Four-Door Car      Medsize              0  

[5 rows x 23 columns]

In [ ]:
#encode categoricals

In [6]:
numerical = marketing_customer_analysis_cleaned_lab6.select_dtypes(include = ['int64', 'float64']) 
categoricals = marketing_customer_analysis_cleaned_lab6.select_dtypes(include = ['object'])

In [7]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(categoricals)
print(encoder.categories_)
encoded = encoder.transform(categoricals).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categoricals)
onehot_encoded.head()

[array(['AA10041', 'AA11235', 'AA16582', ..., 'ZZ89380', 'ZZ91716',
       'ZZ97035'], dtype=object), array(['Arizona', 'California', 'Nevada', 'Oregon', 'Washington'],
      dtype=object), array(['Basic', 'Extended', 'Premium'], dtype=object), array(['Bachelor', 'College', 'Doctor', 'High School or Below', 'Master'],
      dtype=object), array(['Disabled', 'Employed', 'Medical Leave', 'Retired', 'Unemployed'],
      dtype=object), array(['F', 'M'], dtype=object), array(['Rural', 'Suburban', 'Urban'], dtype=object), array(['Divorced', 'Married', 'Single'], dtype=object), array(['Corporate Auto', 'Personal Auto', 'Special Auto'], dtype=object), array(['Corporate L1', 'Corporate L2', 'Corporate L3', 'Personal L1',
       'Personal L2', 'Personal L3', 'Special L1', 'Special L2',
       'Special L3'], dtype=object), array(['Offer1', 'Offer2', 'Offer3', 'Offer4'], dtype=object), array(['Agent', 'Branch', 'Call Center', 'Web'], dtype=object), array(['Four-Door Car', 'Luxury Car', 'Luxury SUV

AttributeError: 'OneHotEncoder' object has no attribute 'categoricals'

In [9]:
categoricals.head(4)

Customer       State  Coverage Education EmploymentStatus Gender  \
0  DK49336     Arizona     Basic   College         Employed      M   
1  KX64629  California     Basic   College       Unemployed      F   
2  LZ68649  Washington     Basic  Bachelor         Employed      M   
3  XL78013      Oregon  Extended   College         Employed      M   

  Location Code Marital Status     Policy Type        Policy Renew Offer Type  \
0      Suburban        Married  Corporate Auto  Corporate L3           Offer3   
1      Suburban         Single   Personal Auto   Personal L3           Offer4   
2      Suburban         Single   Personal Auto   Personal L3           Offer3   
3      Suburban         Single  Corporate Auto  Corporate L3           Offer2   

  Sales Channel  Vehicle Class Vehicle Size  
0         Agent  Four-Door Car      Medsize  
1   Call Center  Four-Door Car      Medsize  
2   Call Center            SUV      Medsize  
3        Branch  Four-Door Car      Medsize

In [10]:
X_cat1=categoricals.drop(['Customer', 'State', 'EmploymentStatus', 'Education', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 


In [11]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(X_cat1)
print(encoder.categories_)

[array(['Basic', 'Extended', 'Premium'], dtype=object)]


In [12]:
X_cat1.head()

Coverage
0     Basic
1     Basic
2     Basic
3  Extended
4   Premium

In [13]:
#assign variabele encoded to transform and convert to array
encoded= encoder.transform(X_cat1).toarray()
print (encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [14]:
# Create a dataframe with columns
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)
onehot_encoded.head()

Basic Extended Premium
0   1.0      0.0     0.0
1   1.0      0.0     0.0
2   1.0      0.0     0.0
3   0.0      1.0     0.0
4   0.0      0.0     1.0

In [15]:
X_cat2=categoricals.drop(['Customer', 'State', 'Coverage', 'Education', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder2 = OneHotEncoder().fit(X_cat2)
print(encoder2.categories_)

[array(['Disabled', 'Employed', 'Medical Leave', 'Retired', 'Unemployed'],
      dtype=object)]


In [16]:
X_cat2.head()

EmploymentStatus
0         Employed
1       Unemployed
2         Employed
3         Employed
4    Medical Leave

In [17]:
encoded1= encoder2.transform(X_cat2).toarray()
print (encoded1)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
onehot_encoded1 = pd.DataFrame(encoded1,columns=encoder2.categories_)
onehot_encoded1.head()

Disabled Employed Medical Leave Retired Unemployed
0      0.0      1.0           0.0     0.0        0.0
1      0.0      0.0           0.0     0.0        1.0
2      0.0      1.0           0.0     0.0        0.0
3      0.0      1.0           0.0     0.0        0.0
4      0.0      0.0           1.0     0.0        0.0

In [19]:
X_cat3=categoricals.drop(['Customer', 'State', 'Coverage', 'EmploymentStatus', 'Gender', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder3 = OneHotEncoder().fit(X_cat3)
print(encoder3.categories_)

[array(['Bachelor', 'College', 'Doctor', 'High School or Below', 'Master'],
      dtype=object)]


In [20]:
X_cat3.head()

Education
0   College
1   College
2  Bachelor
3   College
4  Bachelor

In [21]:
encoded2= encoder3.transform(X_cat3).toarray()
print(encoded2)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [22]:
onehot_encoded2 = pd.DataFrame(encoded1,columns=encoder3.categories_)
onehot_encoded2.head()

Bachelor College Doctor High School or Below Master
0      0.0     1.0    0.0                  0.0    0.0
1      0.0     0.0    0.0                  0.0    1.0
2      0.0     1.0    0.0                  0.0    0.0
3      0.0     1.0    0.0                  0.0    0.0
4      0.0     0.0    1.0                  0.0    0.0

In [23]:
X_cat4=categoricals.drop(['Customer', 'State', 'Coverage', 'EmploymentStatus', 'Education', 'Location Code', 'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Vehicle Class', 'Vehicle Size'],axis=1) 
from sklearn.preprocessing import OneHotEncoder
encoder4 = OneHotEncoder().fit(X_cat4)
print(encoder4.categories_)

[array(['F', 'M'], dtype=object)]


In [24]:
X_cat4.head()

Gender
0      M
1      F
2      M
3      M
4      F

In [25]:
encoded3= encoder4.transform(X_cat4).toarray()
print(encoded3)

[[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [26]:
onehot_encoded3 = pd.DataFrame(encoded3,columns=encoder4.categories_)
onehot_encoded3.head()

F    M
0  0.0  1.0
1  1.0  0.0
2  0.0  1.0
3  0.0  1.0
4  1.0  0.0

In [27]:
#Concat DataFrames

In [28]:
categorical_varables=pd.concat([onehot_encoded,onehot_encoded1,onehot_encoded2,onehot_encoded3],axis=0)

In [29]:
categorical_varables

Bachelor Basic College Disabled Doctor Employed Extended    F  \
0          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
1          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
2          NaN   1.0     NaN      NaN    NaN      NaN      0.0  NaN   
3          NaN   0.0     NaN      NaN    NaN      NaN      1.0  NaN   
4          NaN   0.0     NaN      NaN    NaN      NaN      0.0  NaN   
...        ...   ...     ...      ...    ...      ...      ...  ...   
10905      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10906      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10907      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10908      NaN   NaN     NaN      NaN    NaN      NaN      NaN  1.0   
10909      NaN   NaN     NaN      NaN    NaN      NaN      NaN  0.0   

      High School or Below    M Master Medical Leave Premium Retired  \
0                      NaN  NaN    NaN           NaN     0.0     NaN   
1                      NaN  NaN    NaN           NaN     0.0     NaN   
2                      NaN  NaN    NaN           NaN     0.0     NaN   
3                      NaN  NaN    NaN           NaN     0.0     NaN   
4                      NaN  NaN    NaN           NaN     1.0     NaN   
...                    ...  ...    ...           ...     ...     ...   
10905                  NaN  0.0    NaN           NaN     NaN     NaN   
10906                  NaN  0.0    NaN           NaN     NaN     NaN   
10907                  NaN  0.0    NaN           NaN     NaN     NaN   
10908                  NaN  0.0    NaN           NaN     NaN     NaN   
10909                  NaN  1.0    NaN           NaN     NaN     NaN   

      Unemployed  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
10905        NaN  
10906        NaN  
10907        NaN  
10908        NaN  
10909        NaN  

[43640 rows x 15 columns]

In [30]:
categorical_varables=pd.concat([onehot_encoded,onehot_encoded1,onehot_encoded2,onehot_encoded3],axis=1)

In [31]:
categorical_varables

Basic Extended Premium Disabled Employed Medical Leave Retired  \
0       1.0      0.0     0.0      0.0      1.0           0.0     0.0   
1       1.0      0.0     0.0      0.0      0.0           0.0     0.0   
2       1.0      0.0     0.0      0.0      1.0           0.0     0.0   
3       0.0      1.0     0.0      0.0      1.0           0.0     0.0   
4       0.0      0.0     1.0      0.0      0.0           1.0     0.0   
...     ...      ...     ...      ...      ...           ...     ...   
10905   0.0      0.0     1.0      0.0      0.0           0.0     0.0   
10906   1.0      0.0     0.0      0.0      1.0           0.0     0.0   
10907   0.0      1.0     0.0      0.0      1.0           0.0     0.0   
10908   0.0      0.0     1.0      0.0      1.0           0.0     0.0   
10909   1.0      0.0     0.0      0.0      0.0           0.0     0.0   

      Unemployed Bachelor College Doctor High School or Below Master    F    M  
0            0.0      0.0     1.0    0.0                  0.0    0.0  0.0  1.0  
1            1.0      0.0     0.0    0.0                  0.0    1.0  1.0  0.0  
2            0.0      0.0     1.0    0.0                  0.0    0.0  0.0  1.0  
3            0.0      0.0     1.0    0.0                  0.0    0.0  0.0  1.0  
4            0.0      0.0     0.0    1.0                  0.0    0.0  1.0  0.0  
...          ...      ...     ...    ...                  ...    ...  ...  ...  
10905        1.0      0.0     0.0    0.0                  0.0    1.0  1.0  0.0  
10906        0.0      0.0     1.0    0.0                  0.0    0.0  1.0  0.0  
10907        0.0      0.0     1.0    0.0                  0.0    0.0  1.0  0.0  
10908        0.0      0.0     1.0    0.0                  0.0    0.0  1.0  0.0  
10909        1.0      0.0     0.0    0.0                  0.0    1.0  0.0  1.0  

[10910 rows x 15 columns]

In [ ]:
#Train-test split


In [33]:
numerical

Customer Lifetime Value  Income  Monthly Premium Auto  \
0                  4809.216960   48029                    61   
1                  2228.525238       0                    64   
2                 14947.917300   22139                   100   
3                 22332.439460   49078                    97   
4                  9025.067525   23675                   117   
...                        ...     ...                   ...   
10905             15563.369440       0                   253   
10906              5259.444853   61146                    65   
10907             23893.304100   39837                   201   
10908             11971.977650   64195                   158   
10909              6857.519928       0                   101   

       Months Since Last Claim  Months Since Policy Inception  \
0                     7.000000                             52   
1                     3.000000                             26   
2                    34.000000                             31   
3                    10.000000                              3   
4                    15.149071                             31   
...                        ...                            ...   
10905                15.149071                             40   
10906                 7.000000                             68   
10907                11.000000                             63   
10908                 0.000000                             27   
10909                31.000000                              1   

       Number of Open Complaints  Number of Policies  Total Claim Amount  \
0                       0.000000                   9          292.800000   
1                       0.000000                   1          744.924331   
2                       0.000000                   2          480.000000   
3                       0.000000                   2          484.013411   
4                       0.384256                   7          707.925645   
...                          ...                 ...                 ...   
10905                   0.384256                   7         1214.400000   
10906                   0.000000                   6          273.018929   
10907                   0.000000                   2          381.306996   
10908                   4.000000                   6          618.288849   
10909                   0.000000                   3         1021.719397   

       response Rate  
0                  0  
1                  0  
2                  0  
3                  1  
4                  0  
...              ...  
10905              0  
10906              0  
10907              0  
10908              0  
10909              1  

[10910 rows x 9 columns]

In [46]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(numerical)
x_normalized = MinMaxtransformer.transform(numerical)
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized,columns=numerical.columns)
x_normalized.head()

(10910, 9)


Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.035752  0.480381              0.000000   
1                 0.004059  0.000000              0.012658   
2                 0.160264  0.221432              0.164557   
3                 0.250953  0.490873              0.151899   
4                 0.087527  0.236795              0.236287   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.200000                       0.525253   
1                 0.085714                       0.262626   
2                 0.971429                       0.313131   
3                 0.285714                       0.030303   
4                 0.432831                       0.313131   

   Number of Open Complaints  Number of Policies  Total Claim Amount  \
0                   0.000000               1.000            0.101171   
1                   0.000000               0.000            0.257445   
2                   0.000000               0.125            0.165875   
3                   0.000000               0.125            0.167263   
4                   0.076851               0.750            0.244657   

   response Rate  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            0.0

In [ ]:
#separate the features from the labels

In [37]:
print(numerical['Total Claim Amount'])

0         292.800000
1         744.924331
2         480.000000
3         484.013411
4         707.925645
            ...     
10905    1214.400000
10906     273.018929
10907     381.306996
10908     618.288849
10909    1021.719397
Name: Total Claim Amount, Length: 10910, dtype: float64


In [43]:
X = numerical.drop('Total CLaim Amount', axis =1 )
y = numerical['Total CLaim Amount']
#Total CLaim Amount is written correctly, see above. I (still) cant figure out the error below. 

KeyError: "['Total CLaim Amount'] not found in axis"

In [47]:
#categorical features and numerical ones are going to be treated differently
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = np.object)

NameError: name 'X' is not defined

In [ ]:
# Normalizing and Standardizing data - only for numerical variables

In [48]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(numerical)
x_normalized = MinMaxtransformer.transform(numerical)
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized,columns=numerical.columns)
x_normalized.head()

(10910, 9)


Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.035752  0.480381              0.000000   
1                 0.004059  0.000000              0.012658   
2                 0.160264  0.221432              0.164557   
3                 0.250953  0.490873              0.151899   
4                 0.087527  0.236795              0.236287   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.200000                       0.525253   
1                 0.085714                       0.262626   
2                 0.971429                       0.313131   
3                 0.285714                       0.030303   
4                 0.432831                       0.313131   

   Number of Open Complaints  Number of Policies  Total Claim Amount  \
0                   0.000000               1.000            0.101171   
1                   0.000000               0.000            0.257445   
2                   0.000000               0.125            0.165875   
3                   0.000000               0.125            0.167263   
4                   0.076851               0.750            0.244657   

   response Rate  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            0.0

In [49]:
# let's merge all this information together into a single dataset with all features, now numerical
X = pd.concat([x_normalized, categorical_varables], axis=1)

In [50]:
X.head()

Customer Lifetime Value    Income  Monthly Premium Auto  \
0                 0.035752  0.480381              0.000000   
1                 0.004059  0.000000              0.012658   
2                 0.160264  0.221432              0.164557   
3                 0.250953  0.490873              0.151899   
4                 0.087527  0.236795              0.236287   

   Months Since Last Claim  Months Since Policy Inception  \
0                 0.200000                       0.525253   
1                 0.085714                       0.262626   
2                 0.971429                       0.313131   
3                 0.285714                       0.030303   
4                 0.432831                       0.313131   

   Number of Open Complaints  Number of Policies  Total Claim Amount  \
0                   0.000000               1.000            0.101171   
1                   0.000000               0.000            0.257445   
2                   0.000000               0.125            0.165875   
3                   0.000000               0.125            0.167263   
4                   0.076851               0.750            0.244657   

   response Rate  (Basic,)  ...  (Medical Leave,)  (Retired,)  (Unemployed,)  \
0            0.0       1.0  ...               0.0         0.0            0.0   
1            0.0       1.0  ...               0.0         0.0            1.0   
2            0.0       1.0  ...               0.0         0.0            0.0   
3            1.0       0.0  ...               0.0         0.0            0.0   
4            0.0       0.0  ...               1.0         0.0            0.0   

   (Bachelor,)  (College,)  (Doctor,)  (High School or Below,)  (Master,)  \
0          0.0         1.0        0.0                      0.0        0.0   
1          0.0         0.0        0.0                      0.0        1.0   
2          0.0         1.0        0.0                      0.0        0.0   
3          0.0         1.0        0.0                      0.0        0.0   
4          0.0         0.0        1.0                      0.0        0.0   

   (F,)  (M,)  
0   0.0   1.0  
1   1.0   0.0  
2   0.0   1.0  
3   0.0   1.0  
4   1.0   0.0  

[5 rows x 24 columns]

In [52]:
y = marketing_customer_analysis_cleaned_lab6['Total Claim Amount']
y.head()

0    292.800000
1    744.924331
2    480.000000
3    484.013411
4    707.925645
Name: Total Claim Amount, dtype: float64

In [54]:
# train test split is the way ML generates its claim to fame: we build the model on a portion of the data but we then validate it in another "fresh" portion
# our model has no opportunity to "cheat": it must accurately guess the values in the "fresh" dataset that it never saw before
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 100)

In [55]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8728, 24)
(2182, 24)
(8728,)
(2182,)


In [56]:
X_train.head()

Customer Lifetime Value    Income  Monthly Premium Auto  \
9256                 0.024231  0.000000              0.206751   
5378                 0.272998  0.140747              0.042194   
3963                 0.014047  0.137916              0.075949   
3605                 0.008057  0.000000              0.046414   
5283                 0.042012  0.251388              0.025316   

      Months Since Last Claim  Months Since Policy Inception  \
9256                 0.228571                       0.767677   
5378                 0.371429                       0.030303   
3963                 0.228571                       0.494949   
3605                 0.914286                       0.141414   
5283                 0.085714                       0.000000   

      Number of Open Complaints  Number of Policies  Total Claim Amount  \
9256                        0.0               0.000            0.182466   
5378                        0.0               0.125            0.176660   
3963                        0.0               0.000            0.131034   
3605                        0.0               0.000            0.140230   
5283                        0.0               0.625            0.111125   

      response Rate  (Basic,)  ...  (Medical Leave,)  (Retired,)  \
9256            0.0       1.0  ...               0.0         0.0   
5378            1.0       1.0  ...               1.0         0.0   
3963            0.0       0.0  ...               0.0         0.0   
3605            0.0       1.0  ...               0.0         0.0   
5283            1.0       1.0  ...               0.0         0.0   

      (Unemployed,)  (Bachelor,)  (College,)  (Doctor,)  \
9256            1.0          0.0         0.0        0.0   
5378            0.0          0.0         0.0        1.0   
3963            0.0          1.0         0.0        0.0   
3605            1.0          0.0         0.0        0.0   
5283            0.0          0.0         1.0        0.0   

      (High School or Below,)  (Master,)  (F,)  (M,)  
9256                      0.0        1.0   1.0   0.0  
5378                      0.0        0.0   0.0   1.0  
3963                      0.0        0.0   1.0   0.0  
3605                      0.0        1.0   1.0   0.0  
5283                      0.0        0.0   1.0   0.0  

[5 rows x 24 columns]

In [57]:
X_test.head()

Customer Lifetime Value    Income  Monthly Premium Auto  \
1250                  0.011206  0.267951              0.042194   
5438                  0.008690  0.205959              0.042194   
10156                 0.068202  0.000000              0.194093   
3441                  0.179052  0.498345              0.037975   
682                   0.089584  0.373951              0.236287   

       Months Since Last Claim  Months Since Policy Inception  \
1250                  0.114286                       0.414141   
5438                  0.428571                       0.818182   
10156                 0.171429                       0.636364   
3441                  0.400000                       0.272727   
682                   0.857143                       0.212121   

       Number of Open Complaints  Number of Policies  Total Claim Amount  \
1250                         0.0               0.000            0.117762   
5438                         0.2               0.000            0.067420   
10156                        0.0               0.875            0.266251   
3441                         0.6               0.125            0.116103   
682                          0.0               0.500            0.194080   

       response Rate  (Basic,)  ...  (Medical Leave,)  (Retired,)  \
1250             1.0       1.0  ...               0.0         0.0   
5438             0.0       1.0  ...               0.0         0.0   
10156            0.0       1.0  ...               0.0         0.0   
3441             1.0       1.0  ...               0.0         0.0   
682              0.0       1.0  ...               0.0         0.0   

       (Unemployed,)  (Bachelor,)  (College,)  (Doctor,)  \
1250             0.0          0.0         1.0        0.0   
5438             0.0          0.0         1.0        0.0   
10156            1.0          0.0         0.0        0.0   
3441             0.0          0.0         1.0        0.0   
682              0.0          0.0         1.0        0.0   

       (High School or Below,)  (Master,)  (F,)  (M,)  
1250                       0.0        0.0   0.0   1.0  
5438                       0.0        0.0   0.0   1.0  
10156                      0.0        1.0   0.0   1.0  
3441                       0.0        0.0   1.0   0.0  
682                        0.0        0.0   0.0   1.0  

[5 rows x 24 columns]

In [61]:
from sklearn import linear_model

In [62]:
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [ ]:
# Model Validation R2 MSE RMSE MAE

In [63]:
from sklearn.metrics import mean_squared_error, r2_score

In [64]:
mse = mean_squared_error(y_test, predictions)
print(mse)

NameError: name 'predictions' is not defined

In [65]:
rmse = math.sqrt(mse)
print(rmse)

NameError: name 'math' is not defined

In [66]:
r2 = r2_score(y_test, predictions)
r2

NameError: name 'predictions' is not defined

In [67]:
marketing_customer_analysis_cleaned_lab6.to_csv('marketing_customer_analysis_cleaned_lab7renewed.csv')
